# Generated by Django 5.1.15 on 2026-09-15 05:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Artikul kodi (Model)')),
                ('name', models.CharField(max_length=200, verbose_name='Model nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model / Artikul',
                'verbose_name_plural': 'Modellar / Artikullar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Operatsiya kodi')),
                ('name', models.CharField(max_length=200, verbose_name='Operatsiya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Operatsiya',
                'verbose_name_plural': 'Operatsiyalar katalogi',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ArticleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Dona narxi (UZS)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Ketma-ketlik tartibi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_operations', to='production.article')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_articles', to='production.operation')),
            ],
            options={
                'verbose_name': 'Model operatsiyasi va narxi',
                'verbose_name_plural': 'Model operatsiyalari va narxlari',
                'ordering': ['sequence', 'id'],
                'unique_together': {('article', 'operation')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Buyurtma raqami')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='Jami reja miqdori (dona)')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Buyurtmachi')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('IN_PROGRESS', 'Ishlab chiqarishda'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilindi')], default='IN_PROGRESS', max_length=20, verbose_name='Holati')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.article', verbose_name='Model (Artikul)')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField(verbose_name='Quti raqami')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qutidagi donalar soni')),
                ('status', models.CharField(choices=[('CREATED', 'Yaratildi'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Bajarildi')], default='CREATED', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='production.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Quti (Bundle)',
                'verbose_name_plural': 'Qutilar (Bundles)',
                'ordering': ['order', 'box_number'],
                'unique_together': {('order', 'box_number')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Bilet kodi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ajratilgan dona soni')),
                ('split_index', models.PositiveIntegerField(default=1, verbose_name="Bo'lak indeksi")),
                ('total_splits', models.PositiveIntegerField(default=1, verbose_name="Jami bo'laklar")),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Dona narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami summa (UZS)')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SCANNED', 'Bajarildi (Skanerlangan)')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('screen_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Monitor ekrani (1-10)')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Skanerlangan vaqt')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/tickets/')),
                ('article_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='production.articleoperation', verbose_name='Operatsiya')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='production.box', verbose_name='Quti')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.worker', verbose_name='Tikuvchi')),
            ],
            options={
                'verbose_name': 'Operatsiya QR Bilti',
                'verbose_name_plural': 'Operatsiya QR Biletlari',
                'ordering': ['box', 'article_operation__sequence', 'split_index'],
            },
        ),
    ]
