# Generated by Django 5.1.15 on 2026-09-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.article', verbose_name='Asosiy Model (Artikul)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami reja miqdori (dona)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni (dona)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='production.article', verbose_name='Model (Artikul)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.order', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Zakaz Modeli',
                'verbose_name_plural': 'Zakaz Modellari',
                'unique_together': {('order', 'article')},
            },
        ),
    ]
