# Generated by Django 5.1.15 on 2026-09-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_order_article_alter_order_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='production.article', verbose_name='Model (Artikul)'),
        ),
    ]
