# Generated by Django 5.1.15 on 2026-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_box_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True, verbose_name='Quti Unikal ID (8 talik)'),
        ),
    ]
