# Generated by Django 5.1.15 on 2026-09-15 11:28

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_box_box_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_code',
            field=models.CharField(db_index=True, default=production.models.generate_unique_box_code, max_length=8, unique=True, verbose_name='Quti Unikal ID (8 talik)'),
        ),
    ]
