# Generated by Django 5.1.15 on 2026-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_box_box_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleoperation',
            name='difficulty',
            field=models.FloatField(default=1.0, verbose_name='Qiyinlik darajasi / koeffitsienti'),
        ),
        migrations.AddField(
            model_name='operation',
            name='default_difficulty',
            field=models.FloatField(default=1.0, verbose_name='Standart qiyinlik koeffitsienti'),
        ),
    ]
