# Generated by Django 5.1.15 on 2026-09-17 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_worker_is_active_and_more'),
        ('production', '0006_articleoperation_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Quti raqami'),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Yaratildi'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Bajarildi')], db_index=True, default='CREATED', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Skanerlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screen_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Monitor ekrani (1-10)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SCANNED', 'Bajarildi (Skanerlangan)')], db_index=True, default='PENDING', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'scanned_at'], name='tkt_status_scanned_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['screen_number', 'status', 'scanned_at'], name='tkt_screen_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['worker', 'status', 'scanned_at'], name='tkt_worker_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['box', 'status'], name='tkt_box_stat_idx'),
        ),
    ]
