# Generated by Django 5.1.15 on 2026-09-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_box_box_number_alter_box_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='daily_norm',
            field=models.PositiveIntegerField(default=1500, verbose_name='Kunlik norma (ball / shartli dona)'),
        ),
    ]
