# Generated by Django 5.1.15 on 2026-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_article_daily_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='norm',
            field=models.PositiveIntegerField(default=1000, verbose_name='Model normasi (ball)'),
        ),
    ]
