# Generated by Django 5.1.15 on 2026-09-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_orderitem_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='razmer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Razmer (O'lcham)"),
        ),
    ]
