# Generated by Django 5.1.15 on 2026-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_box_razmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stiker_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True, verbose_name='Stiker Unikal ID (8 talik)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/tickets/%Y/%m/'),
        ),
    ]
