# Generated by Django 5.1.15 on 2026-09-18 15:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_ticket_stiker_code_alter_ticket_qr_code_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Zakazchi (Mijoz) nomi')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kodi / Qisqartmasi')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzili')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif / Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zakazchi (Mijoz)',
                'verbose_name_plural': 'Zakazchilar (Mijozlar)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Model nomi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Model kodi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('daily_norm', models.PositiveIntegerField(default=1000, verbose_name='Kunlik norma (ball / dona)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modellar',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['code'], 'verbose_name': 'Artikul', 'verbose_name_plural': 'Artikullar'},
        ),
        migrations.AlterModelOptions(
            name='articleoperation',
            options={'ordering': ['sequence', 'id'], 'verbose_name': 'Artikul operatsiyasi va narxi', 'verbose_name_plural': 'Artikul operatsiyalari va narxlari'},
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Artikul kodi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='daily_norm',
            field=models.PositiveIntegerField(default=1000, verbose_name='Kunlik norma (ball / shartli dona)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Artikul nomi / Rangi'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='production.customer', verbose_name='Zakazchi (Mijoz)'),
        ),
        migrations.AddField(
            model_name='article',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='production.productmodel', verbose_name='Tegishli Model'),
        ),
        migrations.CreateModel(
            name='ProductModelOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Dona narxi (UZS)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Ketma-ketlik tartibi')),
                ('difficulty', models.FloatField(default=1.0, verbose_name='Qiyinlik darajasi / koeffitsienti')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_operations', to='production.productmodel', verbose_name='Model')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_models', to='production.operation', verbose_name='Operatsiya')),
            ],
            options={
                'verbose_name': 'Model operatsiyasi va narxi',
                'verbose_name_plural': 'Model operatsiyalari va narxlari',
                'ordering': ['sequence', 'id'],
                'unique_together': {('model', 'operation')},
            },
        ),
    ]
