# Generated by Antigravity to sync Box.status with actual Ticket scans

from django.db import migrations


def sync_box_statuses(apps, schema_editor):
    Box = apps.get_model('production', 'Box')
    Ticket = apps.get_model('production', 'Ticket')

    for box in Box.objects.all():
        total = box.tickets.count()
        if total == 0:
            continue
        scanned = box.tickets.filter(status='SCANNED').count()
        if scanned == total:
            new_status = 'COMPLETED'
        elif scanned > 0:
            new_status = 'IN_PROGRESS'
        else:
            new_status = 'CREATED'
        if box.status != new_status:
            box.status = new_status
            box.save(update_fields=['status'])


def reverse_sync(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_customer_productmodel_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RunPython(sync_box_statuses, reverse_sync),
    ]

