# Generated by Django 5.1.15 on 2026-09-19 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_sync_box_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(verbose_name='Kesim Raqami')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Kesim Nomi')),
                ('cutter_name', models.CharField(blank=True, max_length=100, verbose_name='Bichuvchi')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kesilgan vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cutting_batches', to=settings.AUTH_USER_MODEL, verbose_name='Kirituvchi')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_batches', to='production.orderitem', verbose_name='Zakaz Modeli')),
            ],
            options={
                'verbose_name': 'Kesim Partiyasi',
                'verbose_name_plural': 'Kesim Partiyalari',
                'ordering': ['batch_number'],
                'unique_together': {('order_item', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text='Masalan: S, M, L, XL, 38, 40...', max_length=50, verbose_name="Razmer (O'lcham)")),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='Zakaz Reja Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='production.orderitem', verbose_name='Zakaz Modeli')),
            ],
            options={
                'verbose_name': 'Model Razmeri',
                'verbose_name_plural': 'Model Razmerlari',
                'ordering': ['id'],
                'unique_together': {('order_item', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='CuttingBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Kesilgan Soni')),
                ('boxes_created_qty', models.PositiveIntegerField(default=0, verbose_name='Quti Qilingan Soni')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.cuttingbatch', verbose_name='Kesim Partiyasi')),
                ('order_item_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_items', to='production.orderitemsize', verbose_name='Razmer')),
            ],
            options={
                'verbose_name': 'Kesim Razmer Bandi',
                'verbose_name_plural': 'Kesim Razmer Bandlari',
                'unique_together': {('batch', 'order_item_size')},
            },
        ),
    ]
