# Generated by Django 5.1.15 on 2026-09-19 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_cuttingbatch_orderitemsize_cuttingbatchitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='cutting_batch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='production.cuttingbatchitem', verbose_name='Kesim Partiyasi Bandi'),
        ),
        migrations.AddField(
            model_name='box',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Chop etilgan'),
        ),
        migrations.AddField(
            model_name='box',
            name='meto_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meto Raqamlari'),
        ),
        migrations.AddField(
            model_name='box',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan vaqt'),
        ),
        migrations.AddField(
            model_name='cuttingbatch',
            name='fabric_batch_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mato Partiyasi / Rulon'),
        ),
        migrations.AddField(
            model_name='cuttingbatch',
            name='fabric_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Mato Og'irligi (kg)"),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='meto_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Meto Tugatilgan Vaqt'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='meto_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_meto_items', to=settings.AUTH_USER_MODEL, verbose_name='Metochi'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='meto_notes',
            field=models.TextField(blank=True, verbose_name='Meto Izohi (Braklar)'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='meto_number_end',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meto Tugashi'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='meto_number_start',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meto Boshlanishi'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='meto_worker_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Metochi'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='real_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aniq Son (Meto)'),
        ),
        migrations.AddField(
            model_name='cuttingbatchitem',
            name='status',
            field=models.CharField(choices=[('CUT_ENTERED', 'Kesim kiritildi (Meto kutilmoqda)'), ('METO_CONFIRMED', 'Meto tasdiqladi (Stikerlar yaratildi)'), ('STICKERS_PRINTED', 'Stikerlar chop etildi (Tikuvga berildi)')], db_index=True, default='CUT_ENTERED', max_length=30, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='cuttingbatchitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Kesilgan Soni (Kesimchi)'),
        ),
    ]
