# Generated by Django 5.1.15 on 2026-09-19 05:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_box_cutting_batch_item_box_is_printed_box_meto_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyModelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('daily_norm', models.PositiveIntegerField(verbose_name='Kunlik norma (dona)')),
                ('completed_units', models.PositiveIntegerField(default=0, verbose_name='Bugun tikilgan dona')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Bajarilish foizi (%)')),
                ('carried_over_units', models.PositiveIntegerField(default=0, verbose_name="Oldingi kundan o'tgan qoldiq dona")),
                ('carried_over_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Qoldiq foizi (%)')),
                ('total_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Jami hisoblangan foiz (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Norma bajarildimi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='production.productmodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Model Kunlik Norma Natijasi',
                'verbose_name_plural': 'Modellar Kunlik Norma Natijalari',
                'ordering': ['-date', 'product_model'],
                'unique_together': {('product_model', 'date')},
            },
        ),
    ]
