# Generated by Django 5.1.15 on 2026-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_dailymodelprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='pastal_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Pastal raqami (Pastal Code)'),
        ),
    ]
