# Generated by Django 5.1.15 on 2026-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_box_pastal_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['order_number', 'code'], 'verbose_name': 'Operatsiya', 'verbose_name_plural': 'Operatsiyalar katalogi'},
        ),
        migrations.AddField(
            model_name='operation',
            name='order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Standart tartib raqami'),
        ),
    ]
