# Generated by Django 5.1.15 on 2026-09-21 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
        ('production', '0018_alter_operation_options_operation_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muzlatilgan vaqt'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='frozen_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_tickets', to='accounts.workerpayout', verbose_name="Bog'langan oylik to'lovi"),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_frozen',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Muzlatilgan (Qulflangan)'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_frozen', 'status'], name='tkt_frozen_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['worker', 'is_frozen'], name='tkt_worker_frozen_idx'),
        ),
    ]
