# Generated by Django 5.1.15 on 2026-09-21 10:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_ticket_frozen_at_ticket_frozen_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Guruh nomi / Shablon nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operatsiyalar guruhi',
                'verbose_name_plural': 'Operatsiyalar guruhlari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='operation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='production.operationgroup', verbose_name='Operatsiyalar Guruhi (Shablon)'),
        ),
        migrations.CreateModel(
            name='OperationGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Dona narxi (UZS)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Ketma-ketlik tartibi')),
                ('difficulty', models.FloatField(default=1.0, verbose_name='Qiyinlik darajasi / koeffitsienti')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.operationgroup', verbose_name='Guruh')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='production.operation', verbose_name='Operatsiya')),
            ],
            options={
                'verbose_name': 'Guruh operatsiyasi va narxi',
                'verbose_name_plural': 'Guruh operatsiyalari va narxlari',
                'ordering': ['sequence', 'id'],
                'unique_together': {('group', 'operation')},
            },
        ),
    ]
