# Generated by Django 5.1.15 on 2026-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_operationgroup_article_operation_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='Model rasmi'),
        ),
    ]
