# Generated by Django 5.1.15 on 2026-09-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Tayyorlanmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Tugatildi'), ('ARCHIVED', 'Arxivlandi'), ('CANCELLED', 'Bekor qilindi')], default='IN_PROGRESS', max_length=20, verbose_name='Holati'),
        ),
    ]
