# Generated by Django 5.1.15 on 2026-09-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingbatch',
            name='partiya_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Partiya Raqami'),
        ),
        migrations.AddField(
            model_name='cuttingbatch',
            name='pastal_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pastal Kodi'),
        ),
    ]
