# Generated by Django 5.1.15 on 2026-09-23 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_cuttingbatch_partiya_number_cuttingbatch_pastal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='controlled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kontrol qilingan vaqt'),
        ),
        migrations.AddField(
            model_name='box',
            name='controlled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_boxes', to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan kontrolchi'),
        ),
        migrations.AddField(
            model_name='box',
            name='controlled_defect_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Brak (chiqindi) soni'),
        ),
        migrations.AddField(
            model_name='box',
            name='controlled_first_sort_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='1-sort soni'),
        ),
        migrations.AddField(
            model_name='box',
            name='controlled_repair_qty',
            field=models.PositiveIntegerField(default=0, verbose_name="Hozir ta'mirda turgan soni"),
        ),
        migrations.AddField(
            model_name='box',
            name='controlled_second_sort_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='2-sort soni'),
        ),
        migrations.AddField(
            model_name='box',
            name='is_controlled',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Kontroldan o'tgan"),
        ),
        migrations.CreateModel(
            name='BoxQualityInspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INITIAL', 'Birlamchi Tekshiruv'), ('REPAIR_RETURN', "Ta'mirdan Qaytish")], default='INITIAL', max_length=20, verbose_name='Tekshiruv turi')),
                ('inspected_qty', models.PositiveIntegerField(default=0, verbose_name="Ko'rib chiqilgan son")),
                ('first_sort_qty', models.PositiveIntegerField(default=0, verbose_name='1-sort qilingan')),
                ('second_sort_qty', models.PositiveIntegerField(default=0, verbose_name='2-sort qilingan')),
                ('repair_qty', models.PositiveIntegerField(default=0, verbose_name="Ta'mirga yuborilgan")),
                ('defect_qty', models.PositiveIntegerField(default=0, verbose_name='Brak deb topilgan')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspection_logs', to='production.box', verbose_name='Quti')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Kontrolchi')),
            ],
            options={
                'verbose_name': 'Sifat Nazorati Jurnali',
                'verbose_name_plural': 'Sifat Nazorati Jurnallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
