# Generated by Django 5.1.15 on 2026-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_box_controlled_at_box_controlled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Yaratildi'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilingan (Eskirgan)')], db_index=True, default='CREATED', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SCANNED', 'Bajarildi (Skanerlangan)'), ('CANCELLED', 'Bekor qilingan (Eskirgan)')], db_index=True, default='PENDING', max_length=20, verbose_name='Holati'),
        ),
    ]
