# Generated by Django 5.1.15 on 2026-09-25 11:55

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_alter_box_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_code',
            field=models.CharField(
                db_index=True,
                default=production.models.generate_unique_box_code,
                max_length=20,
                unique=True,
                verbose_name='Quti Unikal ID'
            ),
        ),
    ]
