# Generated by Django 5.1.15 on 2026-09-28 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_box_box_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Shablon Kodi')),
                ('name', models.CharField(max_length=255, verbose_name='Brak / Nuqson Sababi')),
                ('category', models.CharField(choices=[('SEWING', 'Tikuvchilik (Chok / Tikuv)'), ('CUTTING', 'Bichuv (Kesim)'), ('FABRIC', 'Mato / Xomashyo'), ('IRONING', 'Dazmol / Tozalash'), ('ACCESSORY', 'Furnitura / Aksessuarlar'), ('OTHER', 'Boshqa nuqsonlar')], default='SEWING', max_length=50, verbose_name="Bo'lim / Kategoriya")),
                ('defect_type', models.CharField(choices=[('REPAIRABLE', "Tuzatsa bo'ladi (Ta'mirga yuborish)"), ('NON_REPAIRABLE', "Tuzatib bo'lmaydi (Brak / 2-sort)"), ('BOTH', 'Ikkala holat uchun ham')], default='REPAIRABLE', max_length=20, verbose_name='Turi / Oqibati')),
                ('description', models.TextField(blank=True, verbose_name='Batafsil tavsif / Izoh')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_defect_reasons', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Brak Sababi Shablon',
                'verbose_name_plural': 'Brak Sabablari Shablonlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
