# Generated by Django 5.1.15 on 2026-10-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_cancelledbatchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleoperation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol / To'xtatilgan"),
        ),
        migrations.AddField(
            model_name='operationgroupitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol / To'xtatilgan"),
        ),
        migrations.AddField(
            model_name='productmodeloperation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name="Faol / To'xtatilgan"),
        ),
    ]
