# Generated by Django 5.1.15 on 2026-10-07 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_articleoperation_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_all_operations_scanned', models.BooleanField(default=False, verbose_name="Qutini qabul qilishda barcha operatsiyalar to'liq skanerlangan bo'lishi shart")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_control_settings', to=settings.AUTH_USER_MODEL, verbose_name='Oxirgi tahrirlovchi')),
            ],
            options={
                'verbose_name': 'OTK Nazorat Sozlamasi',
                'verbose_name_plural': 'OTK Nazorat Sozlamalari',
            },
        ),
    ]
