# Generated by Django 5.1.15 on 2026-10-07 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_controlsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPatokProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.PositiveIntegerField(db_index=True, verbose_name='Patok Raqami')),
                ('patok_code', models.CharField(max_length=20, verbose_name='Patok Kodi')),
                ('date', models.DateField(db_index=True, verbose_name='Sana')),
                ('daily_norm', models.PositiveIntegerField(default=1200, verbose_name='Kunlik Norma (dona)')),
                ('completed_units', models.PositiveIntegerField(default=0, verbose_name='Bajarilgan dona (Dazmol)')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Bajarilish foizi (%)')),
                ('dazmol_qty', models.PositiveIntegerField(default=0, verbose_name="Dazmoldan o'tgan dona")),
                ('scanned_ops_qty', models.PositiveIntegerField(default=0, verbose_name='Jami tikilgan operatsiyalar')),
                ('tickets_count', models.PositiveIntegerField(default=0, verbose_name='Skanerlangan stikerlar soni')),
                ('controlled_qty', models.PositiveIntegerField(default=0, verbose_name="OTK o'tgan dona")),
                ('waiting_qty', models.PositiveIntegerField(default=0, verbose_name='Kutayotgan dona')),
                ('repair_qty', models.PositiveIntegerField(default=0, verbose_name="Ta'mir dona")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Norma bajarildimi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patok Kunlik Norma Natijasi',
                'verbose_name_plural': 'Patoklar Kunlik Norma Natijalari',
                'ordering': ['-date', 'screen_number'],
                'unique_together': {('screen_number', 'date')},
            },
        ),
    ]
