# Generated by Django 5.1.15 on 2026-09-15 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi (UZS)")),
                ('payout_type', models.CharField(choices=[('SALARY', "Oylik to'lov"), ('ADVANCE', 'Avans'), ('BONUS', 'Mukofot / Bonus')], default='ADVANCE', max_length=20, verbose_name="To'lov turi")),
                ('payout_date', models.DateField(verbose_name="To'lov sanasi")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="To'lovchi")),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.worker', verbose_name='Tikuvchi')),
            ],
            options={
                'verbose_name': "Xodimga to'lov / Avans",
                'verbose_name_plural': "Xodimlar to'lovlari va avanslari",
                'ordering': ['-payout_date', '-created_at'],
            },
        ),
    ]
