# Generated by Django 5.1.15 on 2026-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workerpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/users/', verbose_name='QR Kod'),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True, verbose_name='Unikal 6 xonali UID'),
        ),
    ]
