# Generated by Django 5.1.15 on 2026-09-16 07:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_worker_user_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkerClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Hisob sanasi')),
                ('total_units', models.PositiveIntegerField(default=0, verbose_name='Tikilgan donalar')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kunlik ish haqi (UZS)')),
                ('ticket_count', models.PositiveIntegerField(default=0, verbose_name='Biletlar soni')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Yopilgan vaqti')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closings', to='accounts.worker', verbose_name='Tikuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik Ish Haqi Yopilishi',
                'verbose_name_plural': 'Kunlik Ish Haqi Yopilishlari',
                'ordering': ['-date', 'worker'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
