# Generated by Django 5.1.15 on 2026-09-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dailyworkerclosing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='workerpayout',
            name='payout_date',
            field=models.DateField(db_index=True, verbose_name="To'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='workerpayout',
            name='payout_type',
            field=models.CharField(choices=[('SALARY', "Oylik to'lov"), ('ADVANCE', 'Avans'), ('BONUS', 'Mukofot / Bonus')], db_index=True, default='ADVANCE', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AddIndex(
            model_name='dailyworkerclosing',
            index=models.Index(fields=['date', 'worker'], name='daily_date_worker_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayout',
            index=models.Index(fields=['worker', 'payout_date'], name='payout_worker_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayout',
            index=models.Index(fields=['payout_type', 'payout_date'], name='payout_type_date_idx'),
        ),
    ]
