# Generated by Django 5.1.15 on 2026-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_worker_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Menejer'), ('CUTTER', 'Kesimchi (Bichuv)'), ('MASTER', 'Master'), ('USER', 'Oddiy User')], default='USER', max_length=20),
        ),
    ]
