# Generated by Django 5.1.15 on 2026-09-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Menejer'), ('CUTTER', 'Kesimchi (Bichuv)'), ('METO', 'Metochi (Nomerovka)'), ('STICKER', 'Stiker Chiqaruvchi'), ('MASTER', 'Master'), ('USER', 'Oddiy User')], default='USER', max_length=20),
        ),
    ]
