# Generated by Django 5.1.15 on 2026-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_badge_printed',
            field=models.BooleanField(db_index=True, default=False, help_text='Xodimga ID birka (beydjik) chop etib berilganmi?', verbose_name='Birka berilgan / chop etilgan'),
        ),
    ]
