# Generated by Django 5.1.15 on 2026-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_badge_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Menejer'), ('CUTTER', 'Kesimchi (Bichuv)'), ('METO', 'Metochi (Nomerovka)'), ('STICKER', 'Stiker Chiqaruvchi'), ('MASTER', 'Master'), ('CONTROL', 'Kontrolchi (Sifat Nazorati)'), ('USER', 'Oddiy User')], default='USER', max_length=20),
        ),
    ]
