# Generated by Django 5.1.15 on 2026-09-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_create_patok_control_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Menejer'), ('CUTTER', 'Kesimchi (Bichuv)'), ('METO', 'Metochi (Nomerovka)'), ('STICKER', 'Stiker Chiqaruvchi'), ('MASTER', 'Master'), ('CONTROL', 'Kontrolchi (Sifat Nazorati)'), ('SCREEN', 'Ekran (Monitor)'), ('USER', 'Oddiy User')], default='USER', max_length=20),
        ),
    ]
