# Generated by Django 5.1.15 on 2026-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_branch_and_branch_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True, verbose_name='Foydalanuvchi nomi'),
        ),
    ]
