# Generated by Django 5.1.15 on 2026-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('BRANCH_ADMIN', 'Filial Admini'), ('MANAGER', 'Menejer'), ('CUTTER', 'Kesimchi (Bichuv)'), ('METO', 'Metochi (Nomerovka)'), ('STICKER', 'Stiker Chiqaruvchi'), ('MASTER', 'Master'), ('CONTROL', 'Kontrolchi (Sifat Nazorati)'), ('SCREEN', 'Ekran (Monitor)'), ('PLAN', 'Plan (Rejalashtirish)'), ('USER', 'Oddiy User')], default='USER', max_length=20),
        ),
    ]
