upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 100M;

    # Gzip siqish
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Static fayllar (Nginx to'g'ridan-to'g'ri beradi)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Media va QR kodlar (Nginx to'g'ridan-to'g'ri beradi)
    location /media/ {
        alias /app/media/;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Asosiy Django dasturi
    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_read_timeout 180s;
        proxy_connect_timeout 180s;
    }
}

