upstream django_app {
    server web:8000;
}

# 1. HTTP -> HTTPS Redirect
server {
    listen 80;
    server_name tezol.shop www.tezol.shop _;

    # Certbot avtomatik yangilash uchun
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Avtomatik HTTPS ga yo'naltirish
    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. HTTPS Server (SSL)
server {
    listen 443 ssl;
    server_name tezol.shop www.tezol.shop 34.156.34.148 91.99.181.42 _;

    ssl_certificate /etc/letsencrypt/live/tezol.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tezol.shop/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 100M;

    # Gzip siqish
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Static fayllar (Nginx to'g'ridan-to'g'ri beradi)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Media va QR kodlar (Nginx to'g'ridan-to'g'ri beradi)
    location /media/ {
        alias /app/media/;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Asosiy Django dasturi
    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
        proxy_read_timeout 180s;
        proxy_connect_timeout 180s;
    }
}
